"""Public audiobook planning, build, and artifact APIs."""

from yakbox.audiobook.artifacts import (
    ArtifactKind,
    ArtifactRecord,
    InventoryReport,
    inventory_artifacts,
    repair_artifact_metadata,
)
from yakbox.audiobook.build import (
    BuildChangeSummary,
    BuildPreflight,
    BuildProgress,
    BuildProgressCallback,
    BuildResult,
    ReleaseCheck,
    ReleaseDiff,
    assemble_release,
    audition_audiobook,
    build_audiobook,
    check_release,
    diff_releases,
    preflight_audiobook_build,
    preview_audiobook,
    select_build_chapters,
)
from yakbox.audiobook.cache import (
    CacheCleanupPlan,
    CacheEntry,
    CacheInventory,
    apply_cache_cleanup,
    inventory_synthesis_cache,
    plan_cache_cleanup,
)
from yakbox.audiobook.cleanup import (
    CleanupPlan,
    apply_cleanup,
    plan_cleanup,
    purge_trash,
    restore_trash,
)
from yakbox.audiobook.manifest import AudiobookManifest, load_manifest
from yakbox.audiobook.planner import BuildPlan, plan_audiobook
from yakbox.audiobook.shards import (
    ShardManifest,
    export_shard_manifests,
    verify_shard_manifests,
)
from yakbox.audiobook.sources import (
    NormalizedDocument,
    PronunciationAudit,
    PronunciationRuleAudit,
    audit_pronunciations,
    normalize_sources,
)

__all__ = [
    "ArtifactKind",
    "ArtifactRecord",
    "AudiobookManifest",
    "BuildChangeSummary",
    "BuildPlan",
    "BuildPreflight",
    "BuildProgress",
    "BuildProgressCallback",
    "BuildResult",
    "CacheCleanupPlan",
    "CacheEntry",
    "CacheInventory",
    "CleanupPlan",
    "InventoryReport",
    "NormalizedDocument",
    "PronunciationAudit",
    "PronunciationRuleAudit",
    "ReleaseCheck",
    "ReleaseDiff",
    "ShardManifest",
    "apply_cache_cleanup",
    "apply_cleanup",
    "assemble_release",
    "audit_pronunciations",
    "audition_audiobook",
    "build_audiobook",
    "check_release",
    "diff_releases",
    "export_shard_manifests",
    "inventory_artifacts",
    "inventory_synthesis_cache",
    "load_manifest",
    "normalize_sources",
    "plan_audiobook",
    "plan_cache_cleanup",
    "plan_cleanup",
    "preflight_audiobook_build",
    "preview_audiobook",
    "purge_trash",
    "repair_artifact_metadata",
    "restore_trash",
    "select_build_chapters",
    "verify_shard_manifests",
]
